#
#
#
version: '3.1'
#
services:
  database:
    image: mysql:latest
    container_name: mysql-server
    hostname: mysql-server
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /mysql/conf:/etc/mysql/conf.d
      - /mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@SSW0rd
      MYSQL_DATABASE: PUBLIC
      MYSQL_USER: developer
      MYSQL_PASSWORD: pDSSW0rd
    ports:
      - 3306:3306
#
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
