#
# Application Profiles.
# 
---
#
application:
  message: "Hello User!"
dummy:
  type: type-inside-the-war  
server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    hystrix:
      stream:
        enabled: true
    info:
      enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"      
spring:
  thymeleaf:
    cache: false
  application:
    name: sample-app


#
---
#
# local profile
#
---
#
spring:
  profiles: local  
  application:
    name: sb-myapp
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-gnerator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/h2/changelog.yml
#    context: h2
  datasource:
    driverClassName: org.h2.Driver  
    url: jdbc:h2:file:E:\git-repos\sb-demo-app\database\app-db;AUTO_SERVER=true;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
#
---
#
---
#
spring:
  profiles: docker  
  application:
    name: sb-myapp
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-gnerator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/PUBLIC
    username: developer
    password: pDSSW0rd
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/mysql/changelog.yml
#    context: mysql        
#
---
#