## YAML Template.
---
spring:
  application:
    name: sample-app
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-gnerator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/h2/changelog.yml
#    context: local
  datasource:
    url: jdbc:h2:file:E:\git-repos\sb-demo-app\sb-app-db\sb-app-db;AUTO_SERVER=true;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
---
#
#
#
---
spring:
  profiles: local  
  application:
    name: sample-app